---



- name: Mediawiki basic setup
  hosts: wikinode
  remote_user: root
  tasks:
  - name: install wiki packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - bash-completion
      - httpd 
      - php 
      - php-mysqlnd 
      - php-gd 
      - php-xml 
      - mariadb-server 
      - mariadb 
      - php-mbstring 
      - php-json 
      - mod_ssl 
      - php-intl 
      - php-apcu
  - name: open port for http
    firewalld:
      service: http
      permanent: yes
      state: enabled
  - name: open port for https
    firewalld:  
      service: https
      permanent: yes
      state: enabled
  - name: start httpd service
    ansible.builtin.service:
      name: httpd
      state: started
  - name: reload firewalld
    ansible.builtin.service:
      name: firewalld
      state: reloaded